#!/usr/bin/expect

log_user 0

##spawn $env(SHELL) 
##expect {
##	send "touch toto.txt"
##}
##close

spawn ls
expect {
	default { send_user "Error: Cannot find \'getopt.exp\'\n" ; exit 1 }
	"getopt.exp"
}
send_user "\'getopt.exp\' was found.\n"
close

spawn ls
expect {
	default { send_user "Error: Cannot find \'libft\'\n" ; exit 1 }
	"libft"
}
send_user "\'libft\' was found.\n"
close

spawn ls -l
expect {
	default { send_user "Error: Cannot find \'libft\'\n" ; exit 1 }
	"libft"
}
send_user "\'libft\' was found.\n"
close
